SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE FUNCTION [dbo].[fn_Distributor_Exists](@d INT) RETURNS BIT AS BEGIN RETURN (SELECT CASE WHEN EXISTS(SELECT 1 FROM distributordashboard.Distributor WHERE DistributorId=@d) THEN 1 ELSE 0 END) END
GO
